#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Web.Api.v1/Web.Api.v1.csproj", "Web.Api.v1/"]
RUN dotnet restore "./Web.Api.v1/./Web.Api.v1.csproj"
COPY . .
WORKDIR "/src/Web.Api.v1"
RUN dotnet build "./Web.Api.v1.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Web.Api.v1.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
ENV ASPNETCORE_URLS="http://0.0.0.0:80/"
ENV ASPNETCORE_ENVIRONMENT="Development"
EXPOSE 80
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Web.Api.v1.dll"]