FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY "Web.Api.v1/Web.Api.v1.csproj" "Web.Api.v1/Web.Api.v1.csproj"
WORKDIR /src/Web.Api.v1
RUN dotnet publish -r linux-x64 -c Release -o /app --self-contained false --no-restore 
FROM mcr.microsoft.com/dotnet/aspnet:6.0
ENV TZ=Asia/Ho_Chi_Minh
USER root
WORKDIR /app
COPY --from=build /app .
ENV ASPNETCORE_URLS="http://0.0.0.0:80/"
EXPOSE 80
ENTRYPOINT ["dotnet", "Web.Api.v1.dll"]