FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY "Web.Api.v2/Web.Api.v2.csproj" "Web.Api.v2/Web.Api.v2.csproj"
COPY . .
WORKDIR /src/Web.Api.v2
RUN dotnet publish -r linux-x64 --self-contained false "Web.Api.v2.csproj"  -c release -o /app
FROM mcr.microsoft.com/dotnet/aspnet:6.0
ENV TZ=Asia/Ho_Chi_Minh
USER root
WORKDIR /app
COPY --from=build /app .
ENV ASPNETCORE_URLS="http://0.0.0.0:80/"
EXPOSE 80
ENTRYPOINT ["dotnet", "Web.Api.v2.dll"]